"""empty message

Revision ID: 802889b42ea9
Revises: 25f05b64bd5b
Create Date: 2020-03-25 16:19:26.935812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802889b42ea9'
down_revision = '25f05b64bd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('armor', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('damage', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('hp', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('money', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'xp')
    op.drop_column('user', 'money')
    op.drop_column('user', 'level')
    op.drop_column('user', 'hp')
    op.drop_column('user', 'damage')
    op.drop_column('user', 'armor')
    op.drop_table('likes')
    # ### end Alembic commands ###
